# Generated by Django 4.1 on 2022-09-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0003_usuario_estado_usuario_identificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0, null=True, verbose_name='valor')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='estado')),
                ('decision', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10, verbose_name='decision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.usuario', verbose_name='usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.vehículo', verbose_name='vehiculo')),
            ],
        ),
    ]
