# Generated by Django 4.1 on 2022-09-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Anulada', 'Anulada')], default='Abierta', max_length=10, verbose_name='Estado')),
                ('cantidad_detalle', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura', verbose_name='Factura')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='producto.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle',
                'db_table': 'Detalles_factura',
            },
        ),
    ]
