# Generated by Django 4.1 on 2022-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Latoneria', 'Latoneria'), ('Pintura', 'Pintura')], max_length=10)),
            ],
        ),
    ]
