# Generated by Django 4.1 on 2022-09-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
