# Generated by Django 4.1 on 2022-09-26 21:00

from django.db import migrations, models
import miproyecto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Copia de Seguridad', max_length=200)),
                ('archivo', models.FileField(upload_to='backup', validators=[miproyecto.models.validate_file_extension])),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
