# Generated by Django 4.1 on 2022-09-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_usuario_date_created_usuario_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='fecha',
        ),
    ]
